apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000
---   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana_img
        imagePullPolicy: Never
        env:
        - name: GRAF_USER
          valueFrom:
            secretKeyRef:
              name: grafana
              key: user
        - name: GRAF_PASS
          valueFrom:
            secretKeyRef:
              name: grafana
              key: password
        ports:
        - containerPort: 3000