apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  ports:
  - port: 4999
    protocol: TCP
    name: http
  selector:
    app: telegraf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf_img
        ports:
        - containerPort: 4999
        imagePullPolicy: Never
        env:
          - name: INFLUX_USER
            value: schene
          - name: INFLUX_URL
            value: "http://influxdb:8086"
          - name: INFLUX_SKIP_DATABASE_CREATION
            value: "false"
          - name: INFLUX_PASSWORD
            value: "schene42"
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName